name: udacity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - hydra-core=1.3.2
  - matplotlib=3.10.0
  - pandas=2.8.2
  - jupyterlab=4.2.5
  - pip=24.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
