name: train_val_test_split
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=23.3.1
  - requests=2.24.0
  - scikit-learn=1.5.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/Greg-Pina/Udacity_DataAnalyst_NanoDegree/tree/main/D501%20-%20Machine%20Learning%20DevOps/Project-Build-an-ML-Pipeline-Starter-main#egg=wandb-utils&subdirectory=components
